targets:
  $default:
    builders:
      tom_version_builder:version_builder:
        enabled: true
        options:
          output: lib/src/version.g.dart
          includeGitCommit: true

# Configuration for the runner tool (separate from builder configs)
tom_build_runner:
  build_runner:
    exclude-builders:
      - tom_compiler_builder:compiler_builder
