/// Reflection code generator.
///
/// Generates `.r.dart` files containing reflection data structures,
/// invokers, and the `reflectionApi` entry point based on configuration.
library;

// ignore_for_file: deprecated_member_use

import 'dart:io';

import 'package:analyzer/dart/element/element.dart';
import 'package:path/path.dart' as p;

import 'entry_point_analyzer.dart';
import 'reflection_config.dart';

/// Generates reflection code for a Dart project.
///
/// The generator:
/// 1. Parses configuration from `tom_analyzer.yaml`
/// 2. Analyzes entry points to discover types
/// 3. Applies filters to determine what to include
/// 4. Generates `.r.dart` file with reflection data
class ReflectionGenerator {
  /// The configuration for generation.
  final ReflectionConfig config;

  /// Analysis result (populated after analyze()).
  AnalysisResult? _analysisResult;

  /// Import prefix counter.
  int _prefixCounter = 0;

  /// Type to import prefix mapping.
  final Map<String, String> _importPrefixes = {};

  /// Library URI to import prefix mapping.
  final Map<String, String> _libraryPrefixes = {};

  /// Invoker index counter.
  int _invokerCounter = 0;

  /// Declaration index counter (for future use).
  // ignore: unused_field
  int _declarationCounter = 0;

  /// Type index counter.
  int _typeCounter = 0;

  ReflectionGenerator(this.config);

  /// Create a generator from a configuration file.
  factory ReflectionGenerator.fromFile(String path) {
    return ReflectionGenerator(ReflectionConfig.load(path: path));
  }

  /// Create a generator from a YAML map.
  factory ReflectionGenerator.fromMap(Map<String, dynamic> map) {
    return ReflectionGenerator(ReflectionConfig.fromMap(map));
  }

  /// Analyze entry points and discover types.
  Future<AnalysisResult> analyze() async {
    final analyzer = EntryPointAnalyzer(config);
    _analysisResult = await analyzer.analyze();
    return _analysisResult!;
  }

  /// Generate the reflection file.
  ///
  /// Returns the generated code as a string.
  Future<String> generate() async {
    if (_analysisResult == null) {
      await analyze();
    }
    final result = _analysisResult!;

    // Reset counters
    _prefixCounter = 0;
    _importPrefixes.clear();
    _libraryPrefixes.clear();
    _invokerCounter = 0;
    _declarationCounter = 0;
    _typeCounter = 0;

    final buffer = StringBuffer();

    // Header
    _writeHeader(buffer);

    // Imports
    _writeImports(buffer, result);

    // Bit flag constants
    _writeFlagConstants(buffer);

    // Package and library structure
    _writePackageStructure(buffer, result);

    // Invokers array
    _writeInvokers(buffer, result);

    // Reflection data structure
    _writeReflectionData(buffer, result);

    // API initialization
    _writeInitialization(buffer);

    return buffer.toString();
  }

  /// Generate and write to the output file.
  Future<void> generateToFile() async {
    final code = await generate();
    final outputPath = config.getOutputPath();

    // Ensure directory exists
    final dir = Directory(p.dirname(outputPath));
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }

    // Write file
    File(outputPath).writeAsStringSync(code);
  }

  void _writeHeader(StringBuffer buffer) {
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by tom_analyzer reflection generator');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln();
  }

  void _writeImports(StringBuffer buffer, AnalysisResult result) {
    // Runtime import
    buffer.writeln("import 'package:tom_analyzer/reflection_runtime.dart' as r;");
    buffer.writeln();

    // Collect all library URIs that need imports
    final libraryUris = <String>{};

    for (final cls in result.classes) {
      libraryUris.add(cls.library.source.uri.toString());
    }
    for (final enm in result.enums) {
      libraryUris.add(enm.library.source.uri.toString());
    }
    for (final mixin in result.mixins) {
      libraryUris.add(mixin.library.source.uri.toString());
    }
    for (final extType in result.extensionTypes) {
      libraryUris.add(extType.library.source.uri.toString());
    }
    for (final func in result.globalFunctions) {
      libraryUris.add(func.library.source.uri.toString());
    }
    for (final variable in result.globalVariables) {
      libraryUris.add(variable.library.source.uri.toString());
    }

    // Generate imports with prefixes
    for (final uri in libraryUris.toList()..sort()) {
      // Skip dart: imports for now (handled separately)
      if (uri.startsWith('dart:')) continue;

      final prefix = 'p${_prefixCounter++}';
      _libraryPrefixes[uri] = prefix;
      buffer.writeln("import '$uri' as $prefix;");
    }

    buffer.writeln();
  }

  void _writeFlagConstants(StringBuffer buffer) {
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln('// Bit flag constants for element descriptors');
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln();

    // Class flags
    buffer.writeln('// Class flags');
    buffer.writeln('const _abstract = 1 << 0;');
    buffer.writeln('const _mixin = 1 << 1;');
    buffer.writeln('const _sealed = 1 << 2;');
    buffer.writeln('const _final = 1 << 3;');
    buffer.writeln('const _interface = 1 << 4;');
    buffer.writeln('const _base = 1 << 5;');
    buffer.writeln();

    // Member flags
    buffer.writeln('// Member flags');
    buffer.writeln('const _static = 1 << 0;');
    buffer.writeln('const _finalMember = 1 << 1;');
    buffer.writeln('const _const = 1 << 2;');
    buffer.writeln('const _late = 1 << 3;');
    buffer.writeln('const _getter = 1 << 4;');
    buffer.writeln('const _setter = 1 << 5;');
    buffer.writeln('const _method = 1 << 6;');
    buffer.writeln('const _constructor = 1 << 7;');
    buffer.writeln('const _factory = 1 << 8;');
    buffer.writeln('const _extension = 1 << 9;');
    buffer.writeln('const _async = 1 << 10;');
    buffer.writeln('const _generator = 1 << 11;');
    buffer.writeln();
  }

  void _writePackageStructure(StringBuffer buffer, AnalysisResult result) {
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln('// Package and Library Structure');
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln();

    // Packages array
    buffer.writeln('const _packages = <r.PackageData>[');
    var packageIndex = 0;
    final packageIndices = <String, int>{};
    final libraryIndices = <String, int>{};
    var libraryIndex = 0;

    for (final packageName in result.packageLibraries.keys.toList()..sort()) {
      final libraries = result.packageLibraries[packageName]!;
      final libIndices = <int>[];

      for (final libUri in libraries) {
        libraryIndices[libUri] = libraryIndex;
        libIndices.add(libraryIndex);
        libraryIndex++;
      }

      packageIndices[packageName] = packageIndex;
      buffer.writeln(
          "  r.PackageData('$packageName', const ${libIndices.toString()}),  // Index $packageIndex");
      packageIndex++;
    }
    buffer.writeln('];');
    buffer.writeln();

    // Libraries array
    buffer.writeln('const _libraries = <r.LibraryData>[');
    for (final libUri in libraryIndices.keys.toList()..sort()) {
      final packageName = _getPackageFromUri(libUri);
      final pkgIdx = packageIndices[packageName] ?? 0;

      // Get type indices for this library
      final types = result.libraryTypes[libUri] ?? [];
      final typeIndices =
          types.map((t) => _getTypeIndex(t)).where((i) => i >= 0).toList();

      buffer.writeln("  r.LibraryData(");
      buffer.writeln("    '$libUri',");
      buffer.writeln("    $pkgIdx,  // package index");
      buffer.writeln("    const $typeIndices,  // type indices");
      buffer.writeln("    const [],  // declaration indices");
      buffer.writeln("  ),");
    }
    buffer.writeln('];');
    buffer.writeln();
  }

  void _writeInvokers(StringBuffer buffer, AnalysisResult result) {
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln('// Invokers Array');
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln();
    buffer.writeln('const _invokers = <Function>[');

    // Generate invokers for each class
    for (final cls in result.classes) {
      _writeClassInvokers(buffer, cls);
    }

    // Generate invokers for global functions
    for (final func in result.globalFunctions) {
      _writeGlobalFunctionInvoker(buffer, func);
    }

    // Generate invokers for global variables
    for (final variable in result.globalVariables) {
      _writeGlobalVariableInvokers(buffer, variable);
    }

    buffer.writeln('];');
    buffer.writeln();
  }

  void _writeClassInvokers(StringBuffer buffer, ClassElement cls) {
    final prefix = _getPrefix(cls);

    // Skip abstract classes for constructor invokers
    if (!cls.isAbstract) {
      // Constructor invokers
      for (final ctor in cls.constructors) {
        if (ctor.isPrivate) continue;
        if (!_shouldGenerateInvoker(ctor)) continue;

        final ctorName = ctor.name.isEmpty ? 'new' : ctor.name;
        buffer.writeln(
            "  // ${cls.name}.$ctorName constructor - Index ${_invokerCounter++}");
        buffer.writeln(
            "  (List args, Map<Symbol, dynamic> named) => Function.apply($prefix.${cls.name}.$ctorName, args, named),");
      }
    }

    // Instance method invokers
    for (final method in cls.methods) {
      if (method.isPrivate || method.isStatic) continue;
      if (!_shouldGenerateInvoker(method)) continue;

      buffer.writeln(
          "  // ${cls.name}.${method.name} method - Index ${_invokerCounter++}");
      buffer.writeln(
          "  (dynamic i, List args, Map<Symbol, dynamic> named) => Function.apply(i.${method.name}, args, named),");
    }

    // Instance field getters
    for (final field in cls.fields) {
      if (field.isPrivate || field.isStatic) continue;

      buffer.writeln(
          "  // ${cls.name}.${field.name} getter - Index ${_invokerCounter++}");
      buffer.writeln("  (dynamic i) => i.${field.name},");

      // Field setter (if not final/const)
      if (!field.isFinal && !field.isConst) {
        buffer.writeln(
            "  // ${cls.name}.${field.name} setter - Index ${_invokerCounter++}");
        buffer.writeln("  (dynamic i, dynamic v) => i.${field.name} = v,");
      }
    }

    // Static method invokers
    for (final method in cls.methods) {
      if (method.isPrivate || !method.isStatic) continue;
      if (!_shouldGenerateInvoker(method)) continue;

      buffer.writeln(
          "  // ${cls.name}.${method.name} static - Index ${_invokerCounter++}");
      buffer.writeln(
          "  (List args, Map<Symbol, dynamic> named) => Function.apply($prefix.${cls.name}.${method.name}, args, named),");
    }

    // Static field accessors
    for (final field in cls.fields) {
      if (field.isPrivate || !field.isStatic) continue;

      buffer.writeln(
          "  // ${cls.name}.${field.name} static getter - Index ${_invokerCounter++}");
      buffer.writeln("  () => $prefix.${cls.name}.${field.name},");

      if (!field.isFinal && !field.isConst) {
        buffer.writeln(
            "  // ${cls.name}.${field.name} static setter - Index ${_invokerCounter++}");
        buffer.writeln("  (dynamic v) => $prefix.${cls.name}.${field.name} = v,");
      }
    }
  }

  void _writeGlobalFunctionInvoker(StringBuffer buffer, FunctionElement func) {
    if (func.isPrivate) return;

    final prefix = _getPrefix(func);
    buffer.writeln("  // ${func.name} global function - Index ${_invokerCounter++}");
    buffer.writeln(
        "  (List args, Map<Symbol, dynamic> named) => Function.apply($prefix.${func.name}, args, named),");
  }

  void _writeGlobalVariableInvokers(
      StringBuffer buffer, TopLevelVariableElement variable) {
    if (variable.isPrivate) return;

    final prefix = _getPrefix(variable);
    buffer.writeln(
        "  // ${variable.name} global getter - Index ${_invokerCounter++}");
    buffer.writeln("  () => $prefix.${variable.name},");

    if (!variable.isFinal && !variable.isConst) {
      buffer.writeln(
          "  // ${variable.name} global setter - Index ${_invokerCounter++}");
      buffer.writeln("  (dynamic v) => $prefix.${variable.name} = v,");
    }
  }

  void _writeReflectionData(StringBuffer buffer, AnalysisResult result) {
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln('// Reflection Data Structure');
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln();
    buffer.writeln('final _reflectionData = r.ReflectionData(');
    buffer.writeln('  packages: _packages,');
    buffer.writeln('  libraries: _libraries,');
    buffer.writeln('  invokers: _invokers,');
    buffer.writeln();

    // Types array
    buffer.writeln('  types: <r.TypeMirrorData>[');
    for (final cls in result.classes) {
      _writeClassMirrorData(buffer, cls);
    }
    for (final enm in result.enums) {
      _writeEnumMirrorData(buffer, enm);
    }
    for (final mixin in result.mixins) {
      _writeMixinMirrorData(buffer, mixin);
    }
    buffer.writeln('  ],');
    buffer.writeln();

    // Declarations array
    buffer.writeln('  declarations: <r.DeclarationMirrorData>[');
    // Generate declaration data for each type
    buffer.writeln('    // Declaration data goes here');
    buffer.writeln('  ],');
    buffer.writeln();

    // Parameters array
    buffer.writeln('  parameters: <r.ParameterMirrorData>[');
    buffer.writeln('    // Parameter data goes here');
    buffer.writeln('  ],');
    buffer.writeln();

    // Type refs array
    buffer.writeln('  typeRefs: <Type>[');
    for (final cls in result.classes) {
      final prefix = _getPrefix(cls);
      buffer.writeln('    $prefix.${cls.name},');
    }
    for (final enm in result.enums) {
      final prefix = _getPrefix(enm);
      buffer.writeln('    $prefix.${enm.name},');
    }
    buffer.writeln('  ],');
    buffer.writeln(');');
    buffer.writeln();
  }

  void _writeClassMirrorData(StringBuffer buffer, ClassElement cls) {
    final prefix = _getPrefix(cls);
    final typeIndex = _typeCounter++;
    final flags = _computeClassFlags(cls);

    buffer.writeln('    // Index $typeIndex: ${cls.name}');
    buffer.writeln('    r.ClassMirrorData<$prefix.${cls.name}>(');
    buffer.writeln("      '${cls.name}',  // name");
    buffer.writeln('      $flags,  // flags');
    buffer.writeln('      0,  // library index');
    buffer.writeln('      const [],  // own declaration indices');
    buffer.writeln('      const [],  // all instance members');
    buffer.writeln('      const [],  // static member indices');
    buffer.writeln('      -1,  // superclass type index');
    buffer.writeln('      const [],  // interface type indices');
    buffer.writeln('      const [],  // mixin type indices');
    buffer.writeln('      const [],  // applicable extension indices');
    buffer.writeln('      const [],  // annotation indices');
    buffer.writeln('      const [],  // constructor invoker indices');
    buffer.writeln('    ),');
  }

  void _writeEnumMirrorData(StringBuffer buffer, EnumElement enm) {
    final prefix = _getPrefix(enm);
    final typeIndex = _typeCounter++;

    buffer.writeln('    // Index $typeIndex: ${enm.name}');
    buffer.writeln('    r.EnumMirrorData<$prefix.${enm.name}>(');
    buffer.writeln("      '${enm.name}',  // name");
    buffer.writeln('      0,  // flags');
    buffer.writeln('      0,  // library index');
    buffer.writeln('      const [],  // value names');
    buffer.writeln('      const [],  // annotation indices');
    buffer.writeln('    ),');
  }

  void _writeMixinMirrorData(StringBuffer buffer, MixinElement mixin) {
    final prefix = _getPrefix(mixin);
    final typeIndex = _typeCounter++;

    buffer.writeln('    // Index $typeIndex: ${mixin.name}');
    buffer.writeln('    r.MixinMirrorData<$prefix.${mixin.name}>(');
    buffer.writeln("      '${mixin.name}',  // name");
    buffer.writeln('      0,  // flags');
    buffer.writeln('      0,  // library index');
    buffer.writeln('      const [],  // superclass constraints');
    buffer.writeln('      const [],  // declaration indices');
    buffer.writeln('      const [],  // annotation indices');
    buffer.writeln('    ),');
  }

  void _writeInitialization(StringBuffer buffer) {
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln('// Runtime API Initialization');
    buffer.writeln('// ═══════════════════════════════════════════════════════════════════');
    buffer.writeln();
    buffer.writeln('void initializeReflection() {');
    buffer.writeln('  r.registerReflectionData(_reflectionData);');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('final reflectionApi = r.ReflectionApi.fromData(_reflectionData);');
  }

  int _computeClassFlags(ClassElement cls) {
    var flags = 0;
    if (cls.isAbstract) flags |= 1 << 0;
    if (cls.isMixinClass) flags |= 1 << 1;
    if (cls.isSealed) flags |= 1 << 2;
    if (cls.isFinal) flags |= 1 << 3;
    if (cls.isInterface) flags |= 1 << 4;
    if (cls.isBase) flags |= 1 << 5;
    return flags;
  }

  String _getPrefix(Element element) {
    final uri = element.library?.source.uri.toString();
    if (uri == null) return '';
    return _libraryPrefixes[uri] ?? '';
  }

  String _getPackageFromUri(String uri) {
    if (uri.startsWith('package:')) {
      final path = uri.substring('package:'.length);
      final slashIndex = path.indexOf('/');
      return slashIndex > 0 ? path.substring(0, slashIndex) : path;
    }
    if (uri.startsWith('dart:')) {
      return uri;
    }
    return 'unknown';
  }

  int _getTypeIndex(InterfaceElement element) {
    // TODO: Implement proper type index tracking
    return -1;
  }

  bool _shouldGenerateInvoker(Element element) {
    // Check coverage config
    if (element is ConstructorElement) {
      if (!config.coverageConfig.constructors.enabled) return false;
      final pattern = config.coverageConfig.constructors.pattern;
      if (pattern != null && pattern.isNotEmpty) {
        final name = element.name;
        if (name.isEmpty) {
          return config.coverageConfig.constructors.unnamed;
        }
        return GlobMatcher(pattern).matches(name);
      }
      return true;
    }

    if (element is MethodElement) {
      if (element.isStatic) {
        return config.coverageConfig.staticMembers.enabled;
      } else {
        if (!config.coverageConfig.instanceMembers.enabled) return false;
        final pattern = config.coverageConfig.instanceMembers.pattern;
        if (pattern != null && pattern.isNotEmpty) {
          return GlobMatcher(pattern).matches(element.name);
        }
        return true;
      }
    }

    return true;
  }
}

/// Simple glob pattern matcher (duplicated from filter_matcher.dart for independence).
class GlobMatcher {
  final String pattern;
  late final RegExp _regex;

  GlobMatcher(this.pattern) {
    _regex = _compileGlob(pattern);
  }

  bool matches(String input) {
    return _regex.hasMatch(input);
  }

  static RegExp _compileGlob(String pattern) {
    final buffer = StringBuffer('^');
    var i = 0;
    while (i < pattern.length) {
      final c = pattern[i];
      if (c == '*') {
        if (i + 1 < pattern.length && pattern[i + 1] == '*') {
          buffer.write('.*');
          i += 2;
        } else {
          buffer.write('[^/]*');
          i++;
        }
      } else if (c == '?') {
        buffer.write('.');
        i++;
      } else if (r'\.+[]{}()^$|'.contains(c)) {
        buffer.write('\\$c');
        i++;
      } else {
        buffer.write(c);
        i++;
      }
    }
    buffer.write(r'$');
    return RegExp(buffer.toString());
  }
}
