import 'package:test/test.dart';
import 'package:tom_build_base/tom_build_base_v2.dart';

void main() {
  // Create a test tool definition for completion tests
  late ToolDefinition testTool;

  setUp(() {
    testTool = ToolDefinition(
      name: 'mytool',
      version: '1.0.0',
      description: 'Test tool for completion',
      commands: [
        CommandDefinition(
          name: 'build',
          description: 'Build the project',
          aliases: ['b'],
          options: [
            OptionDefinition.flag(
              name: 'release',
              abbr: 'r',
              description: 'Build in release mode',
            ),
            OptionDefinition.option(
              name: 'target',
              abbr: 't',
              description: 'Build target',
            ),
          ],
        ),
        CommandDefinition(
          name: 'test',
          description: 'Run tests',
          options: [
            OptionDefinition.flag(
              name: 'verbose',
              abbr: 'v',
              description: 'Verbose output',
            ),
          ],
        ),
      ],
      globalOptions: [
        OptionDefinition.flag(
          name: 'help',
          abbr: 'h',
          description: 'Show help',
        ),
        OptionDefinition.flag(
          name: 'version',
          description: 'Show version',
        ),
      ],
    );
  });

  group('ShellType', () {
    test('BB-CMP-1: Has three values [2026-02-12]', () {
      expect(ShellType.values, hasLength(3));
      expect(ShellType.values, contains(ShellType.bash));
      expect(ShellType.values, contains(ShellType.zsh));
      expect(ShellType.values, contains(ShellType.fish));
    });
  });

  group('CompletionGenerator.generateBash', () {
    test('BB-CMP-2: Generates bash completion script [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains('# Bash completion for mytool'));
      expect(script, contains('# Generated by tom_build_base v2'));
    });

    test('BB-CMP-3: Includes completion function [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains('_mytool_completions()'));
      expect(script, contains('_init_completion || return'));
    });

    test('BB-CMP-4: Includes commands [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains(':build'));
      expect(script, contains(':test'));
    });

    test('BB-CMP-5: Includes command aliases [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains(':b'));
    });

    test('BB-CMP-6: Includes global options [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains('--help'));
      expect(script, contains('-h'));
      expect(script, contains('--version'));
    });

    test('BB-CMP-7: Includes command-specific options [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains('--release'));
      expect(script, contains('-r'));
      expect(script, contains('--target'));
      expect(script, contains('--verbose'));
    });

    test('BB-CMP-8: Registers completion [2026-02-12]', () {
      final script = CompletionGenerator.generateBash(testTool);

      expect(script, contains('complete -F _mytool_completions mytool'));
    });

    test('BB-CMP-9: Handles tool with no commands [2026-02-12]', () {
      final emptyTool = ToolDefinition(
        name: 'empty',
        version: '1.0.0',
        description: 'Empty tool',
        commands: [],
        globalOptions: [
          OptionDefinition.flag(name: 'help', description: 'Help'),
        ],
      );

      final script = CompletionGenerator.generateBash(emptyTool);

      expect(script, contains('# Bash completion for empty'));
      expect(script, contains('--help'));
    });
  });

  group('CompletionGenerator.generateZsh', () {
    test('BB-CMP-10: Generates zsh completion script [2026-02-12]', () {
      final script = CompletionGenerator.generateZsh(testTool);

      expect(script, contains('#compdef mytool'));
      expect(script, contains('# Zsh completion for mytool'));
      expect(script, contains('# Generated by tom_build_base v2'));
    });

    test('BB-CMP-11: Includes commands array [2026-02-12]', () {
      final script = CompletionGenerator.generateZsh(testTool);

      expect(script, contains('local -a commands'));
      expect(script, contains("':build:Build the project'"));
      expect(script, contains("':test:Run tests'"));
    });

    test('BB-CMP-12: Includes global options array [2026-02-12]', () {
      final script = CompletionGenerator.generateZsh(testTool);

      expect(script, contains('local -a global_opts'));
      expect(script, contains("'-h[Show help]'"));
      expect(script, contains("'--help[Show help]'"));
      expect(script, contains("'--version[Show version]'"));
    });

    test('BB-CMP-13: Includes completion function [2026-02-12]', () {
      final script = CompletionGenerator.generateZsh(testTool);

      expect(script, contains('_mytool()'));
      expect(script, contains('_arguments -C'));
      expect(script, contains('_describe -t commands'));
    });

    test('BB-CMP-14: Includes command-specific options [2026-02-12]', () {
      final script = CompletionGenerator.generateZsh(testTool);

      expect(script, contains("'-r[Build in release mode]'"));
      expect(script, contains("'--release[Build in release mode]'"));
      expect(script, contains("'-t[Build target]'"));
      expect(script, contains("'--target[Build target]'"));
    });

    test('BB-CMP-15: Calls completion function [2026-02-12]', () {
      final script = CompletionGenerator.generateZsh(testTool);

      expect(script, contains('_mytool "\$@"'));
    });
  });

  group('CompletionGenerator.generateFish', () {
    test('BB-CMP-16: Generates fish completion script [2026-02-12]', () {
      final script = CompletionGenerator.generateFish(testTool);

      expect(script, contains('# Fish completion for mytool'));
      expect(script, contains('# Generated by tom_build_base v2'));
    });

    test('BB-CMP-17: Disables file completion [2026-02-12]', () {
      final script = CompletionGenerator.generateFish(testTool);

      expect(script, contains('complete -c mytool -f'));
    });

    test('BB-CMP-18: Includes commands [2026-02-12]', () {
      final script = CompletionGenerator.generateFish(testTool);

      expect(script, contains('# Commands'));
      expect(
          script,
          contains(
              'complete -c mytool -n "__fish_use_subcommand" -a ":build" -d "Build the project"'));
      expect(
          script,
          contains(
              'complete -c mytool -n "__fish_use_subcommand" -a ":test" -d "Run tests"'));
    });

    test('BB-CMP-19: Includes global options [2026-02-12]', () {
      final script = CompletionGenerator.generateFish(testTool);

      expect(script, contains('# Global options'));
      expect(
          script,
          contains(
              'complete -c mytool -s h -l help -d "Show help"'));
      expect(
          script, contains('complete -c mytool -l version -d "Show version"'));
    });

    test('BB-CMP-20: Includes command-specific options [2026-02-12]', () {
      final script = CompletionGenerator.generateFish(testTool);

      expect(script, contains('# :build options'));
      expect(
          script,
          contains(
              'complete -c mytool -n "__fish_seen_subcommand_from :build" -s r -l release -d "Build in release mode"'));
      expect(
          script,
          contains(
              'complete -c mytool -n "__fish_seen_subcommand_from :build" -s t -l target -d "Build target"'));
    });
  });

  group('ToolDefinitionCompletion extension', () {
    test('BB-CMP-21: GenerateCompletion returns bash script [2026-02-12]', () {
      final script = testTool.generateCompletion(ShellType.bash);

      expect(script, contains('# Bash completion for mytool'));
      expect(script, contains('_mytool_completions()'));
    });

    test('BB-CMP-22: GenerateCompletion returns zsh script [2026-02-12]', () {
      final script = testTool.generateCompletion(ShellType.zsh);

      expect(script, contains('#compdef mytool'));
      expect(script, contains('_mytool()'));
    });

    test('BB-CMP-23: GenerateCompletion returns fish script [2026-02-12]', () {
      final script = testTool.generateCompletion(ShellType.fish);

      expect(script, contains('# Fish completion for mytool'));
      expect(script, contains('complete -c mytool'));
    });
  });

  group('Edge cases', () {
    test('BB-CMP-24: Handles options without abbreviations [2026-02-12]', () {
      final tool = ToolDefinition(
        name: 'noabbr',
        version: '1.0.0',
        description: 'Tool without abbreviations',
        commands: [
          CommandDefinition(
            name: 'cmd',
            description: 'Command',
            options: [
              OptionDefinition.option(
                name: 'long-option',
                description: 'A long option without abbreviation',
              ),
            ],
          ),
        ],
        globalOptions: [],
      );

      final bash = CompletionGenerator.generateBash(tool);
      final zsh = CompletionGenerator.generateZsh(tool);
      final fish = CompletionGenerator.generateFish(tool);

      expect(bash, contains('--long-option'));
      expect(zsh, contains("'--long-option[A long option without abbreviation]'"));
      expect(fish, contains('-l long-option'));
    });

    test('BB-CMP-25: Handles descriptions with special characters [2026-02-12]', () {
      final tool = ToolDefinition(
        name: 'special',
        version: '1.0.0',
        description: "Tool with 'special' chars",
        commands: [
          CommandDefinition(
            name: 'cmd',
            description: "It's a \"command\" with special chars",
            options: [],
          ),
        ],
        globalOptions: [],
      );

      // Should not throw
      final bash = CompletionGenerator.generateBash(tool);
      final zsh = CompletionGenerator.generateZsh(tool);
      final fish = CompletionGenerator.generateFish(tool);

      expect(bash.length, greaterThan(0));
      expect(zsh.length, greaterThan(0));
      expect(fish.length, greaterThan(0));
    });

    test('BB-CMP-26: Handles multiple command aliases [2026-02-12]', () {
      final tool = ToolDefinition(
        name: 'aliased',
        version: '1.0.0',
        description: 'Tool with aliases',
        commands: [
          CommandDefinition(
            name: 'build',
            description: 'Build',
            aliases: ['b', 'compile', 'make'],
            options: [],
          ),
        ],
        globalOptions: [],
      );

      final bash = CompletionGenerator.generateBash(tool);

      expect(bash, contains(':build'));
      expect(bash, contains(':b'));
      expect(bash, contains(':compile'));
      expect(bash, contains(':make'));
    });

    test('BB-CMP-27: Handles empty options and commands [2026-02-12]', () {
      final tool = ToolDefinition(
        name: 'minimal',
        version: '1.0.0',
        description: 'Minimal tool',
        commands: [
          CommandDefinition(
            name: 'noop',
            description: 'Does nothing',
            options: [],
          ),
        ],
        globalOptions: [],
      );

      final bash = CompletionGenerator.generateBash(tool);
      final zsh = CompletionGenerator.generateZsh(tool);
      final fish = CompletionGenerator.generateFish(tool);

      expect(bash, contains(':noop'));
      expect(zsh, contains("':noop:Does nothing'"));
      expect(fish, contains('":noop"'));
    });
  });

  group('Helper method tests', () {
    test('BB-CMP-28: _getCommandsStr includes commands and aliases [2026-02-12]', () {
      // Test internal method behavior through output
      final bash = CompletionGenerator.generateBash(testTool);

      // Commands string should appear in completion setup
      expect(bash, contains(':build'));
      expect(bash, contains(':b'));
      expect(bash, contains(':test'));
    });

    test('BB-CMP-29: _getGlobalOptsStr includes all global options [2026-02-12]', () {
      final bash = CompletionGenerator.generateBash(testTool);

      // Global opts should include short and long versions
      expect(bash, contains('-h'));
      expect(bash, contains('--help'));
      expect(bash, contains('--version'));
    });

    test('BB-CMP-30: _getCommandOptsStr includes command options [2026-02-12]', () {
      final bash = CompletionGenerator.generateBash(testTool);

      // Command-specific options should appear
      expect(bash, contains('-r'));
      expect(bash, contains('--release'));
      expect(bash, contains('-t'));
      expect(bash, contains('--target'));
      expect(bash, contains('-v'));
      expect(bash, contains('--verbose'));
    });
  });
}
