// GENERATED FILE - DO NOT EDIT
// Generated by versioner at 2026-02-18T16:15:00.000000Z

/// Version information generated at build time.
///
/// This class contains static fields and methods for accessing
/// version information embedded during the build process.
class IssueKitVersionInfo {
  IssueKitVersionInfo._();

  /// Package version from pubspec.yaml
  static const String version = '1.0.0';

  /// Build timestamp (ISO 8601 UTC format)
  static const String buildTime = '2026-02-18T16:15:00.000000Z';

  /// Git commit hash (short form)
  static const String gitCommit = 'unknown';

  /// Build number (increments with each build)
  static const int buildNumber = 1;

  /// Whether this is a development/debug build
  static const bool isDebug = true;

  /// Git branch name (if available)
  static const String gitBranch = 'unknown';

  /// Returns a formatted version string including build info
  static String get fullVersion => '$version+$buildNumber';

  /// Returns version info as a map
  static Map<String, dynamic> toMap() => {
    'version': version,
    'buildTime': buildTime,
    'gitCommit': gitCommit,
    'buildNumber': buildNumber,
    'isDebug': isDebug,
    'gitBranch': gitBranch,
  };
}
