import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:build/build.dart';

/// Configuration for the version builder.
class VersionBuilderConfig {
  final String output;
  final bool includeGitCommit;

  const VersionBuilderConfig({
    this.output = 'lib/src/version.g.dart',
    this.includeGitCommit = true,
  });

  /// Load from build.yaml options.
  factory VersionBuilderConfig.fromOptions(Map<String, dynamic> options) {
    return VersionBuilderConfig(
      output: options['output'] as String? ?? 'lib/src/version.g.dart',
      includeGitCommit: options['includeGitCommit'] as bool? ?? true,
    );
  }
}

/// Build_runner builder for version file generation.
///
/// Generates a version.g.dart file with package version, build timestamp,
/// git commit hash, build number, and Dart SDK version.
class VersionBuilder implements Builder {
  final VersionBuilderConfig config;

  VersionBuilder(this.config);

  @override
  Map<String, List<String>> get buildExtensions => {
        r'$lib$': ['version.g.info'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final packageName = buildStep.inputId.package;

    // Read pubspec.yaml for version
    String version = '0.0.0';
    try {
      // Build step doesn't have direct file access, so we use the current dir
      final pubspecFile = File('pubspec.yaml');
      if (pubspecFile.existsSync()) {
        final content = pubspecFile.readAsStringSync();
        final match =
            RegExp(r'^version:\s*(.+)$', multiLine: true).firstMatch(content);
        if (match != null) {
          version = match.group(1)!.trim();
        }
      }
    } catch (_) {}

    // Get git commit
    String? gitCommit;
    if (config.includeGitCommit) {
      gitCommit = await _getGitCommit();
    }

    // Get build number
    final buildNumber = _getAndIncrementBuildNumber();

    // Get Dart SDK version
    final dartSdkVersion = await _getDartSdkVersion();

    // Build timestamp
    final buildTime = DateTime.now().toUtc().toIso8601String();

    // Generate content
    final content = _generateVersionFileContent(
      packageName: packageName,
      version: version,
      buildTime: buildTime,
      gitCommit: gitCommit,
      buildNumber: buildNumber,
      dartSdkVersion: dartSdkVersion,
    );

    // Write the output file
    final outputFile = File(config.output);
    outputFile.parent.createSync(recursive: true);
    outputFile.writeAsStringSync(content);

    log.info('Generated ${config.output} for $packageName v$version');
  }

  Future<String?> _getGitCommit() async {
    try {
      final result = await Process.run(
        'git',
        ['rev-parse', '--short', 'HEAD'],
      );
      if (result.exitCode == 0) {
        return result.stdout.toString().trim();
      }
    } catch (_) {}
    return null;
  }

  int _getAndIncrementBuildNumber() {
    final stateFile = File('tom_build_state.json');
    int buildNumber = 1;

    if (stateFile.existsSync()) {
      try {
        final content = stateFile.readAsStringSync();
        final json = jsonDecode(content) as Map<String, dynamic>;
        buildNumber = (json['buildNumber'] as int? ?? 0) + 1;
      } catch (_) {}
    }

    try {
      stateFile.writeAsStringSync(
        const JsonEncoder.withIndent('  ').convert({
          'buildNumber': buildNumber,
          'lastBuild': DateTime.now().toUtc().toIso8601String(),
        }),
      );
    } catch (_) {}

    return buildNumber;
  }

  Future<String?> _getDartSdkVersion() async {
    try {
      final result = await Process.run('dart', ['--version']);
      final output = result.stdout.toString() + result.stderr.toString();
      final match = RegExp(r'Dart SDK version:\s+(\S+)').firstMatch(output);
      if (match != null) return match.group(1);
      final versionMatch = RegExp(r'(\d+\.\d+\.\d+)').firstMatch(output);
      return versionMatch?.group(1);
    } catch (_) {
      return null;
    }
  }

  String _generateVersionFileContent({
    required String packageName,
    required String version,
    required String buildTime,
    String? gitCommit,
    int? buildNumber,
    String? dartSdkVersion,
  }) {
    final gitLine = gitCommit != null
        ? "  static const String gitCommit = '$gitCommit';"
        : "  static const String gitCommit = '';";
    final buildNumLine = buildNumber != null
        ? '  static const int buildNumber = $buildNumber;'
        : '  static const int buildNumber = 0;';
    final sdkLine = dartSdkVersion != null
        ? "  static const String dartSdkVersion = '$dartSdkVersion';"
        : "  static const String dartSdkVersion = '';";

    return '''// GENERATED FILE - DO NOT EDIT
// Generated by versioner at $buildTime

/// Version information generated at build time.
///
/// This class contains static fields and methods for accessing
/// version information embedded during the build process.
class TomVersionInfo {
  TomVersionInfo._();

  /// Package version from pubspec.yaml
  static const String version = '$version';

  /// Build timestamp (ISO 8601 UTC format)
  static const String buildTime = '$buildTime';

  /// Git commit hash (short form)
$gitLine

  /// Build number (increments with each build)
$buildNumLine

  /// Dart SDK version used to build
$sdkLine

  /// Short version string: version + build number
  /// Example: "1.0.0+42"
  static String get versionShort => '\$version+\$buildNumber';

  /// Medium version string: version + build number + git commit + build time
  /// Example: "1.0.0+42.abc1234 (2026-02-01T10:30:00.000Z)"
  static String get versionMedium => '\$version+\$buildNumber.\$gitCommit (\$buildTime)';

  /// Long version string: includes all available information including SDK version
  /// Example: "1.0.0+42.abc1234 (2026-02-01T10:30:00.000Z) [Dart 3.x.x]"
  static String get versionLong => '\$version+\$buildNumber.\$gitCommit (\$buildTime) [Dart \$dartSdkVersion]';
}
''';
  }
}
